# DB 설정
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_member
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

# 카프카 세팅
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9091,localhost:9092,localhost:9093
          zkNodes: localhost:2181,localhost:2182,localhost:2183
      function:
        definition: teamUpdated;teamDeleted;
      bindings:
        teamUpdated-in-0:
          destination: team-updated-topic
        teamDeleted-in-0:
          destination: team-deleted-topic

server:
  port: 8085