# DB 세팅
spring:
  datasource:
    url: jdbc:h2:mem:test_team
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  # 카프카 세팅
  cloud:
    stream:
      bindings:
        teamUpdated:
          destination: team-updated-topic
        teamDeleted:
          destination: team-deleted-topic
      kafka:
        binder:
          brokers: localhost:9091,localhost:9092,localhost:9093
          zkNodes: localhost:2181,localhost:2182,localhost:2183
server:
  port: 8086
